#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Disable download from the default nuclei-templates project
export DISABLE_NUCLEI_TEMPLATES_PUBLIC_DOWNLOAD=true

# Disable download from public / private GitHub project(s)
export DISABLE_NUCLEI_TEMPLATES_GITHUB_DOWNLOAD=true

# Disable download from public / private GitLab project(s)
export DISABLE_NUCLEI_TEMPLATES_GITLAB_DOWNLOAD=true

# Disable download from public / private AWS Bucket(s)
export DISABLE_NUCLEI_TEMPLATES_AWS_DOWNLOAD=true

# Disable download from public / private Azure Blob Storage
export DISABLE_NUCLEI_TEMPLATES_AZURE_DOWNLOAD=true


$DIR/bin/download https://github.com/projectdiscovery/nuclei-templates/archive/refs/tags/v9.9.1.zip /tmp/nuclei-templates.zip > /dev/null 2>&1
$DIR/bin/busybox unzip -d /tmp /tmp/nuclei-templates.zip > /dev/null 2>&1

# This will create a /tmp/nuclei-templates-X.X.X directory, change it to /tmp/nuclei-templates
mv /tmp/nuclei-templates-* /tmp/nuclei-templates > /dev/null 2>&1
$DIR/bin/nuclei $@